name: Download, Compile and Build a Wheel of pysqlite3 for Windows
on:
  push:
      branches:
          - test_wheel
  pull_request:
      branches:
      - test_wheel
jobs:
  sqlite_wheel:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download SQLite
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://www.sqlite.org/2024/sqlite-amalgamation-3470000.zip" -OutFile "sqlite-amalgamation.zip"
      - name: Extract SQLite
        shell: pwsh
        run: tar -xzf sqlite-amalgamation.zip -C . --strip-components=1
      - name: Install Python Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
      - name: Build pysqlite3
        run: python setup.py build_static build
      - name: Create pysqlite3 wheel
        run: python -m pip wheel . -w wheelhouse/
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pysqlite3-wheel
          path: wheelhouse/*.whl
      - name: Upload Wheel Artifact as Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "pysqlite3 release ${{ github.ref_name }}"
          draft: false
          prerelease: false
      - name: Upload Wheel to Release
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: wheelhouse/*.whl
          asset_name: ""
          asset_content_type: application/octet-stream